### ISSUE TITLE
Hello Carlos

### ISSUE THREAD

**Issue by darksis** [carlosferry/inspircd#1]
Hello this possible if do you can build a module protection from botnet flood?
this a botnet can inside with address off people and flood this not run off from proxy

**Comment by carlosferry** [comment]
I've written IP-based flood detectors tools in the past. If these botnets are not ran out of proxies, then scanning typical ports for these (8080, 80, 3128, 6588) is not the way to go. What type of botnet attacks do you typically receive? any pattern (that is likely to be repeated) that you could come up with?

**Comment by darksis** [comment]
do you have this a module?

**Comment by darksis** [comment]
the botnet attacks is search address off people and them inside without proxy

**Comment by carlosferry** [comment]
do clones join determined channels?

**Comment by darksis** [comment]
no them join very fast in server and inside to my channel if do you have something module protection about it i happy to try it

**Comment by carlosferry** [comment]
Have you tried using m_connflood.cpp?

**Comment by darksis** [comment]
yes but is not work like something fast this a clone very fast connect

**Comment by carlosferry** [comment]
OK. I will think about something and will get back to you, alright?

**Comment by darksis** [comment]
ok thanks a lot
