### ISSUE TITLE
Hello  carlos

### ISSUE THREAD

**Issue by darksis** [carlosferry/inspircd#2]
Hello  carlos i hope you are not forget about a module protection from flood botnet and more thing for to know yesterday someone flood botnet in my network and this to be very fast this a botnet search ip and address from a people and he inside them,, and sorry about issues again thanks

**Comment by carlosferry** [comment]
May I get the name of your IRC address? I have some ideas flowing around, yet I don't know if you might like these.

**Comment by darksis** [comment]
yes this my address ./server irc.iibbaa.com:6663
